### ISSUE TITLE
Running the generator seems to fail on Node.js 10.14.1

### ISSUE THREAD

**Issue by Narev** [JelteMX/generator-mendix-widget#2]
After running the command yo mendix-widget it asks some questsions creates some files afterwards and when it is done it runs the npm install command which seems to fail on the babel-helpers

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! Unexpected end of JSON input while parsing near '..."name":"babel-helper-'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pieter\AppData\Roaming\npm-cache\_logs\2018-12-04T14_14_44_306Z-debug.log

[2018-12-04T14_14_44_306Z-debug.log](https://github.com/JelteMX/generator-mendix-widget/files/2644319/2018-12-04T14_14_44_306Z-debug.log)

**Comment by JelteMX** [comment]
Could you please reinstall yeoman and the generator? `npm install yo generator-mendix-widget -g`. I am thinking one of the packages hasn't been installed/downloaded properly. I tested this myself this morning (installed it on a fresh node 10.14.1 installation, Windows 10) and it works properly, so my guess is one of the packages might be corrupt.

**Comment by Narev** [comment]
Thx it is now working again.

I did the following: 
	npm uninstall yo generator-mendix-widget -g
	completely removed node.js
	reboot
	installing node.js
	reboot
        npm install yo generator-mendix-widget -g
